Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -25,6 +25,10 @@ jobs:
       run: |
         cd REST_API  # Change to the directory containing your FastAPI code
         DOCKER_TAG=${{ github.event.release.tag_name }}
+        if [ -z "$DOCKER_TAG" ]; then
+          echo "ERROR: Release tag is empty."
+          exit 1
+        fi
         docker build -t sajedul5/task_devops:${DOCKER_TAG} .
         docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
         docker push sajedul5/task_devops:${DOCKER_TAG}
